name: dslink_localschedule
version: 2.0.4
description: Schedule DSLink
dependencies:
  dslink:
    git: https://github.com/IOT-DSA/sdk-dslink-dart.git
  http: ">=0.11.2 <0.12.0"
  timezone: "^0.5.0-dev-2"
  package_config: "^1.0.0"
  xml: "^2.4.0"
dev_dependencies:
  test: "0.12.15+8"
dependency_overrides:
  source_span: "1.4.1"
